@component('components.form.form-group',['field' => $field,'label' => $label ?? null])
    @slot('control')
        <textarea class="form-control summernote" name="{{$field}}" id="{{$field}}"
                  @if(isset($readonly) && $readonly) readonly @endif

                  style="display: none;"></textarea>
    @endslot
@endcomponent
@push('component_scripts')
    <script>
        $(function () {
        var summernote = $('#{{$field}}').summernote({
            height: '{{$height ?? '200px'}}'
        });
        @if(isset($required) && $required)
        $('#{{$formId??''}}').submit(function (e) {
            var code = $('#{{$field}}').summernote('code');
            // <p><br></p> is code generated by Summernote for empty content
            var valid = (code !== '' && code !== '<p><br></p>');
            if (!valid) {
                e.preventDefault();
                $.notify({
                    // options
                    message: 'ЮЛЯ!!!!!!!!!!!!!!!!!!! ЗАПОЛНИ - {{$label}}!'
                }, {
                    placement: {align: 'center'},
                    type: 'danger'
                });
            }
        });
        @endif
        $('#{{$field}}').summernote('code',{!!json_encode($value)!!});
        });

    </script>@endpush
