<?php

namespace App\Http\Requests\Auth;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ConfirmEmailPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => ['required', 'string', 'email', 'max:255',
                Rule::unique('users')->ignore(auth()->user()->id),
            ],
        ];
    }

    public function messages()
    {
        return [
            'email.unique' => 'Email уже зарегестрирован',
            'email' => 'Неверный email'
        ]; // TODO: Change the autogenerated stub
    }
}
